### PR TITLE
Do rest of staff page functionality

### PR DESCRIPTION
**Pull request by mattlack15**

### CODE REVIEW

**Review by gracelliu — APPROVED** [review]
looks ugly af. need fix. (will fix)

good job with the actual code tho lol

**Review by gracelliu — APPROVED** [review]
lgtm

**Review by charlescheung22 — APPROVED** [review]
LGTM!

**Comment by zoeyzlee** [comment]
thanks for finishing up the staff page, i see u've been updating a lot of classes for the Employee stuff. The UI for TrainOperator and TrainEngineer was incomplete b4 but I see u've completed it between the week. Overall code look good just remember to add MORE javadocs. I will be unit testing everything as usual!!

**Pull request merged**
