### PR TITLE
Added persistence to EmployeeTracker

### PR DESCRIPTION
**Pull request by mattlack15**

### CODE REVIEW

**Review by charlescheung22 — APPROVED** [review]
LGTM

**Review by gracelliu — APPROVED** [review]
LGTM!

**Review by Binhe-Jia — DISMISSED** [review]
Yes

**Review by zoeyzlee — DISMISSED** [review]

**Review by charlescheung22 — APPROVED** [review]
LGTM

**Review by gracelliu — APPROVED** [review]
Looks good to me!

**Review by Binhe-Jia — APPROVED** [review]

**Review by gracelliu — COMMENTED** [review]
hi

**Review by zoeyzlee — COMMENTED** [review]
Thanks for writing all the persistence code! the get, save, read, and remove methods look great. I don't think you need 2 get methods though. 

I'm writing the unit tests for these classes, so I will be changing some stuff so it works 👍. All the classes in the Employee package need to implement Serializable to store them in a persistent storage mechanism. To handle edge cases more thoroughly, you should change the 'equals()' and 'hashcode()' methods. I think you also need to do a 'clear()' method in MemoryEmployeeDataStore.

**Pull request merged**
