### PR TITLE
complete EmployeeInteractorTest fix

### PR DESCRIPTION
**Pull request by charlescheung22**
Merging changes to main, four other interactor tests TODO

### CODE REVIEW

**Comment by charlescheung22** [comment]
dont close branch after merge

**Comment by charlescheung22** [comment]
TODO:
TicketInteractorTest (painful)
StatInteractorTest (StatInteractor currently being refactored in another branch)

**Review by zoeyzlee — DISMISSED** [review]
charles pls review the changes and then i think we're good to go to merge

**Review by Binhe-Jia — DISMISSED** [review]

**Review by zoeyzlee — APPROVED** [review]
please resolve the issues before merging. also, you only need 1 reviewer next time u do a pull request

**Comment by charlescheung22** [comment]
Requested all review for fastest response time

**Pull request merged**
